import { readdir, readFile, writeFile } from "node:fs/promises";
import { assembleEdition } from "./generate.ts";
import type { MarketSnapshot } from "./markets.ts";
import { EditionDraft } from "./schema.ts";
import { checkDraft } from "./validate.ts";

// Builds supabase/seed.sql and supabase/setup.sql from the example editions in seeds/.
// Each seed goes through the same checks and assembly as a generated edition.
//
//   npm run seeds

const seedsDir = new URL("../seeds/", import.meta.url);
const supabaseDir = new URL("../../supabase/", import.meta.url);

interface SeedFile {
  date: string;
  generated_at: string;
  model: string;
  markets: MarketSnapshot;
  draft: unknown;
}

const statements: string[] = [];
for (const file of (await readdir(seedsDir)).filter((name) => name.endsWith(".json")).sort()) {
  const seed = JSON.parse(await readFile(new URL(file, seedsDir), "utf8")) as SeedFile;
  const draft = EditionDraft.parse(seed.draft);
  const problems = checkDraft(draft);
  if (problems.length) throw new Error(`${file}: ${problems.join("; ")}`);
  const edition = assembleEdition(seed.date, draft, seed.markets, {
    seenUrls: null,
    warnings: [],
    model: seed.model,
    generatedAt: seed.generated_at,
  });
  const json = JSON.stringify(edition);
  if (json.includes("$seed$")) throw new Error(`${file}: content contains the SQL quote marker`);
  const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
  statements.push(
    `insert into public.editions (edition_date, number, big_story, content, schema_version, model, published_at)
values (${quote(edition.date)}, ${edition.number}, ${quote(edition.big_story.text)}, $seed$${json}$seed$::jsonb, ${edition.schema_version}, ${quote(edition.model)}, ${quote(edition.generated_at)})
on conflict (edition_date) do nothing;`,
  );
  const stories = edition.sections.reduce((sum, section) => sum + section.stories.length, 0);
  console.log(`${file}: No. ${edition.number}, ${stories} stories, ${edition.reading_minutes} min`);
}

const seedSql = `-- Example editions so the app has something to show before the pipeline runs.
-- Generated by \`npm run seeds\` in pipeline/ from pipeline/seeds/*.json. Don't edit by hand.

${statements.join("\n\n")}
`;
const schemaSql = await readFile(new URL("schema.sql", supabaseDir), "utf8");
await writeFile(new URL("seed.sql", supabaseDir), seedSql);
await writeFile(
  new URL("setup.sql", supabaseDir),
  `-- Everything in one go: paste into Supabase → SQL Editor → New query → Run.
-- Generated by \`npm run seeds\` from schema.sql and seed.sql. Don't edit by hand.

${schemaSql}
${seedSql}`,
);
console.log("Wrote supabase/seed.sql and supabase/setup.sql");
